title: Balint Szabo
tagline: Red team research and offensive security
description: Red team research and offensive security

url: "https://bsdrip.github.io"

github:
  username: bsdrip

twitter:
  username: b2dr1p

social:
  name: Balint Szabo
  email: # leave blank or add one
  links:
    - https://github.com/bsdrip
    - https://twitter.com/b2dr1p

theme_mode: dark

avatar: # path to a profile picture if you want one, e.g. /assets/img/avatar.jpg

timezone: Europe/Budapest
